apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubesentient.fullname" . }}-api
  labels:
    {{- include "kubesentient.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kubesentient.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "kubesentient.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      serviceAccountName: {{ include "kubesentient.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: WEAVIATE_URL
              value: "http://{{ include "kubesentient.fullname" . }}-weaviate:8080"
